### PR TITLE
Support for PHP Code Coverage 6.0

### PR DESCRIPTION
**Pull request by bartosz-maciaszek**
Looks like there's not too much to do to use the newer version. Needed to run the library in Sf4 environment.

### CODE REVIEW

**Comment by bartosz-maciaszek** [comment]
Or not :(

`could not reflect class SebastianBergmann\CodeCoverage\CodeCoverage as it is marked final.`

**Comment by ek9** [comment]
Thank you for contribution but PhpSpec 6.0 support will definitely will need more checks and we will need to update the dependent package versions accordingly.

I have made #19 issue to track comment and changes to the package for PhpSpec v6 support
 Do not hesitate to provide feedback on the issue #19

Closing this PR for now.

**Comment by bartosz-maciaszek** [comment]
Thanks for your response @ek9. Just to be clear, my PR was created to address the compatibility with `phpunit/php-code-coverage:~6.0` and not phpspec itself (4.3.0 the latest stable version of `phpspec/phpspec`).

**Comment by ek9** [comment]
Sorry I was in a rush and mis-named #19 issue. Please see #19 for more information on why this was not yet merged (we need to at least fix/update tests as they break due to phpunit/php-code-coverage:6.0 marking their classes as final). This is an issue in our package that needs addressing.

**Pull request closed without merging**
